# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: burrunan/gradle-cache-action@v1
        name: Build EnviumMod-1.16.5

        with:
          job-id: jdk8
          arguments: build
          gradle-version: 6.8.3-bin
